matrix:
- name: Markdown
  sources:
  - '**/*.qmd'
  default_encoding: utf-8
  aspell:
    lang: en
  dictionary:
    wordlists:
    - inst/WORDLIST.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
