name: Bug Report
description: Something is not working correctly or is not working at all!
title: "Bug: <Insert Issue Title Here>"
labels: ["bug", "programming"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        **Example:** Bug: Link is returning a **404 File no found** page
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what were you expecting to happen before the bug?
      placeholder: "Please give us as many details as you can!"
    validations:
      required: true
