name: General Issue
description: Issue that is difficult to fit into bug, or new blog post issue.
title: "General Issue: <Insert Issue Title Here>"
labels: ["general issue"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        **Example:** General Issue: Linked In Blog Post for updates on the latest admiral release?
  - type: textarea
    id: background
    attributes:
      label: Background Information
      description: Please provide a description of a general issue with the Blogs. Links and screenshots are encouraged.
      placeholder: "Example:  Use changelog/news.md file to gather relevant changes and create into a nice post for Linked In.  The more information the better and the faster we can get this issue completed."
    validations:
      required: true
