name:  Updates or Enhancements for Documentation
description: Documents out of date?  Examples need reworking?
title: "Documentation:  <Insert Issue Title Here>"
labels: ["Documentation"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        The Pharmaverse team loves to keep documentations up to date!
  - type: textarea
    id: docs-out-if-sync
    attributes:
      label: Let us know where something needs a refresh or put your idea here!
      description: Screen shots are super helpful here!  You can do a screenshot and cut and paste it here right in here.
      placeholder: "Something is out of sync or needs a refresh"
    validations:
      required: true
