name: Spellcheck
on:
  pull_request:
    branches: ['main']
jobs:
  Spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::spelling
            any::testthat
            any::readr

      - name: Remove links from .qmd files (Bash)
        run: |
          find . -type f -name "*.qmd" -print0 | while IFS= read -r -d '' file; do
              sed -i -E '
                  s/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/\1/g;  # Remove Markdown links, keep text
                  s#https?://[a-zA-Z0-9./?=_-]+(\#[a-zA-Z0-9_-]*)?##g  # Remove standalone URLs, including fragments
              ' "$file"
              echo "Processed: $file"
          done
        shell: bash

      - name: Check spelling
        run: |
          library(spelling)
          library(readr)

          qmd_files <- list.files(pattern = ".*\\.qmd$", recursive = TRUE)

          words <- spelling::spell_check_files(
            qmd_files,
            ignore = read_lines("inst/WORDLIST.txt")
          )

          print(words)

          testthat::test_that(desc = "Check spelling", code = {
            testthat::expect_equal(
              object = words,
              expected = spelling::spell_check_files(
                path = "inst/WORDLIST.txt",
                ignore = read_lines("inst/WORDLIST.txt")
              )
            )
          })
        shell: Rscript {0}
